package team2485.smartdashboard.extension;

import edu.wpi.first.smartdashboard.gui.Widget;
import edu.wpi.first.smartdashboard.properties.Property;
import edu.wpi.first.smartdashboard.types.DataType;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class LargeText extends Widget {
    public static final String NAME = "Large Text";
    public static final DataType[] TYPES = { DataType.NUMBER, DataType.STRING };

    @Override
    public void init() {
        initComponents();
        this.titleLabel.setText(this.getFieldName());

        final JPanel self = this;
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // force net border
                self.setBorder(new team2485.smartdashboard.extension.util.NiceBorder(Color.white, 1, 6, 5));
            }
        });
    }

    @Override
    public void setValue(Object o) {
        if (o instanceof Number)
            this.valueLabel.setText((Number)o + "");
        else if (o instanceof String)
            this.valueLabel.setText((String)o);
    }

    @Override
    public void propertyChanged(Property prprt) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 17, 17));
        setBorder(new team2485.smartdashboard.extension.util.NiceBorder(Color.white, 1, 6, 5));
        setMaximumSize(new java.awt.Dimension(32767, 61));
        setMinimumSize(new java.awt.Dimension(100, 61));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(300, 61));

        titleLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Title");

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(valueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(3, 3, 3)
                .addComponent(valueLabel))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
